'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MacGen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addspaces_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addspaces_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addspaces_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addspaces_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backcolor_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backcolor_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backcolor_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backcolor_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property CNCView() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CNCView", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property colorize_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorize_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property colorize_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorize_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ColorPicker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColorPicker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copy_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copy_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.cncedit.com/basicviewer/default.aspx?VersionInfo=.
        '''</summary>
        Friend ReadOnly Property datBasicViewerUrl() As String
            Get
                Return ResourceManager.GetString("datBasicViewerUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \x20*.
        '''</summary>
        Friend ReadOnly Property datContractSpaces() As String
            Get
                Return ResourceManager.GetString("datContractSpaces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Support@cncedit.com.
        '''</summary>
        Friend ReadOnly Property datEmail() As String
            Get
                Return ResourceManager.GetString("datEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GOTO?\x20?[0-9]+.
        '''</summary>
        Friend ReadOnly Property datGOTORegex() As String
            Get
                Return ResourceManager.GetString("datGOTORegex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EDAD0E4A-C3CD-4e02-942A-E708C65D8396.
        '''</summary>
        Friend ReadOnly Property datGUID() As String
            Get
                Return ResourceManager.GetString("datGUID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BasicViewer_V1.
        '''</summary>
        Friend ReadOnly Property datProductName() As String
            Get
                Return ResourceManager.GetString("datProductName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^.*.
        '''</summary>
        Friend ReadOnly Property datRegExEntireLineMatch() As String
            Get
                Return ResourceManager.GetString("datRegExEntireLineMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [-+]?[0-9]*[\.,]?[0-9]*.
        '''</summary>
        Friend ReadOnly Property datRegexNcWords() As String
            Get
                Return ResourceManager.GetString("datRegexNcWords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [0-9\.,][A-Z].
        '''</summary>
        Friend ReadOnly Property datRegExpandSpaces() As String
            Get
                Return ResourceManager.GetString("datRegExpandSpaces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [0-9]+[\.,]?[0-9]*.
        '''</summary>
        Friend ReadOnly Property datRegExSeqNumberMatch() As String
            Get
                Return ResourceManager.GetString("datRegExSeqNumberMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \x00\x00|\x0A\x0D\x0D|[\x00-\x09]|[\x0E-\x1F]|[\x7F-\xFF].
        '''</summary>
        Friend ReadOnly Property datRegJunkFilter() As String
            Get
                Return ResourceManager.GetString("datRegJunkFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.CncEdit.com/Deploy/.
        '''</summary>
        Friend ReadOnly Property datWebDeployFolder() As String
            Get
                Return ResourceManager.GetString("datWebDeployFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.cncedit.com.
        '''</summary>
        Friend ReadOnly Property datWebUrl() As String
            Get
                Return ResourceManager.GetString("datWebUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property display_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("display_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property display_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("display_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elementdetails_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elementdetails_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elementdetails_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elementdetails_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error parsing values..
        '''</summary>
        Friend ReadOnly Property ErrorParsingValues() As String
            Get
                Return ResourceManager.GetString("ErrorParsingValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter Range Error.
        '''</summary>
        Friend ReadOnly Property FilterRangeError() As String
            Get
                Return ResourceManager.GetString("FilterRangeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fourscreens_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourscreens_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fourscreens_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourscreens_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Isometric_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Isometric_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mail_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Measure() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Measure", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MeasureKeypoint() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MeasureKeypoint", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property motion_color_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("motion_color_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property motion_color_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("motion_color_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to download.
        '''</summary>
        Friend ReadOnly Property msgClickToDownload() As String
            Get
                Return ResourceManager.GetString("msgClickToDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete setup file and all settings?.
        '''</summary>
        Friend ReadOnly Property msgConfirmDelete() As String
            Get
                Return ResourceManager.GetString("msgConfirmDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connecting....
        '''</summary>
        Friend ReadOnly Property msgConnecting() As String
            Get
                Return ResourceManager.GetString("msgConnecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No updates available at this time.
        '''</summary>
        Friend ReadOnly Property msgNoUpdatesAvailable() As String
            Get
                Return ResourceManager.GetString("msgNoUpdatesAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save changes?.
        '''</summary>
        Friend ReadOnly Property msgPromptToSave() As String
            Get
                Return ResourceManager.GetString("msgPromptToSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One or more GOTO targets are no longer valid..
        '''</summary>
        Friend ReadOnly Property msgRenumberBadGOTO() As String
            Get
                Return ResourceManager.GetString("msgRenumberBadGOTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicate sequence numbers resequenced. Check GOTO targets..
        '''</summary>
        Friend ReadOnly Property msgRenumberDuplicateSequenceNumbers() As String
            Get
                Return ResourceManager.GetString("msgRenumberDuplicateSequenceNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slow graphics performance has been detected.
        '''This happens when the graphics are too large for the world. 
        '''Adjust the precision in viewer setup to correct this.
        '''Click Yes to cancel drawing..
        '''</summary>
        Friend ReadOnly Property msgSlowGfxPerf() As String
            Get
                Return ResourceManager.GetString("msgSlowGfxPerf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to connect.
        '''</summary>
        Friend ReadOnly Property msgUnableToConnect() As String
            Get
                Return ResourceManager.GetString("msgUnableToConnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newfile_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newfile_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newfile_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newfile_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newscheme_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newscheme_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newscheme_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newscheme_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property onescreen_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("onescreen_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property onescreen_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("onescreen_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Options_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Options_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pan_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pan_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pauseplayer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pauseplayer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pauseplayer_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pauseplayer_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property play_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property play_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plot_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plot_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plot_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plot_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property print_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property print_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PrintHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property removespaces_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("removespaces_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property removespacing_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("removespacing_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rename_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rename_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rename_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rename_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property savefile_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savefile_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property savefile_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savefile_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property savefileas_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savefileas_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property savefileas_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savefileas_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property screens_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screens_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property screens_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screens_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property select_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("select_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property select_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("select_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property selectcolor_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectcolor_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property selectcolor_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectcolor_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SelectEtc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectEtc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SelectOne() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectOne", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SetRotate() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SetRotate", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showaxisindicator_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showaxisindicator_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showaxisindicator_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showaxisindicator_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showaxislimits_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showaxislimits_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showaxislimits_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showaxislimits_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showaxislines_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showaxislines_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showaxislines_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showaxislines_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showrapidlines_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showrapidlines_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showrapidlines_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showrapidlines_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showrapidpoints_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showrapidpoints_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showrapidpoints_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showrapidpoints_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property startplayer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startplayer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property startplayer_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startplayer_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stopplayer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stopplayer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stopplayer_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stopplayer_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toggleedit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toggleedit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toggleedit_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toggleedit_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toolsfilter_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolsfilter_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toolsfilter_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolsfilter_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property touchmode_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("touchmode_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property touchmode_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("touchmode_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property twoscreens_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twoscreens_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property twoscreens_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twoscreens_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upper limit must be greater than lower limit..
        '''</summary>
        Friend ReadOnly Property UpperLimitMustBeGreaterThanLowerLimit() As String
            Get
                Return ResourceManager.GetString("UpperLimitMustBeGreaterThanLowerLimit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewfence_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewfence_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewfence_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewfence_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewfit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewfit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewfit_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewfit_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewfront_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewfront_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewfront_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewfront_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewiso_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewiso_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewiso_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewiso_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewoptions_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewoptions_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewoptions_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewoptions_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewpan_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewpan_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewpan_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewpan_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewright_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewright_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewright_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewright_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewrotate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewrotate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewrotate_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewrotate_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewrotate_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewrotate_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewtop_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewtop_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewtop_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewtop_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewzoom_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewzoom_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewzoom_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewzoom_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property website_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("website_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property website_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("website_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zfilter_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zfilter_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zfilter_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zfilter_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zoom_auto_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom_auto_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zoom_auto_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom_auto_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
